apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-express
spec:
  selector:
    matchLabels:
      app: node-express
  replicas: 2
  template:
    metadata:
      labels:
        app: node-express
    spec:
      containers:
        - name: node-express
          image: kahshiu/k-node-express:v1.0.1
          # hardcode environment variables
          env:
            - name: COMMIT
              value: "333"
          #  - name: ENV
          #    value: "production"
          # NOTE: not so grea, mapping value per entry!
            - name: ENV
              valueFrom:
                configMapKeyRef:
                  name: k-node-express-config
                  key: ENV
