apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-express
spec:
  selector:
    matchLabels:
      app: node-express
  replicas: 2
  template:
    metadata:
      labels:
        app: node-express
    spec:
      containers:
        - name: node-express
          image: kahshiu/k-node-express:1.0.0
