apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: node-express
    namespace: argocd
spec:
    destination:
        namespace: my-test
        server: "https://kubernetes.default.svc"
    project: default
    source:
        path: k-node-express
        repoURL: "https://github.com/kahshiu/k-config.git"
        targetRevision: main
    syncPolicy:
        syncOptions:
            - CreateNamespace=true